### ISSUE TITLE
Add MFTF tests to Travis build

### ISSUE THREAD

**Issue by sivaschenko** [magento/adobe-stock-integration#321]
Add MFTF tests to Travis build

# TODO

- [x] fix pathvalidator issue; try not using the `ext/` dir and instead place module code directly in `app/code/Magento/.`
- [x] need to store credentials in MFTF appropriately, filed in #698
- [x] enable https on the travis magento instance
- [x] make sure the adobe.io integration api + private key used in travis has specified the correct redirect uri (matches domain used in travis) - this will likely only be an issue for the signinsignout and signincreditsvisible tests (since those log into adobe ims)
- [x] MFTF preparedness of magento2 instance needs to be done
- tests run a long time, how to optimize?
  - [x] split up test runs across different builds using a build matrix?
  - get more detailed info on timing for each test - filed issue in https://github.com/magento/magento2-functional-testing-framework/issues/508
  - can we save any time on startup? ~5 mins are spent just setting the magento instance up.
    - [x] cache any downloads, i.e. chromedriver?
    - [x] to use caching, ensure 'build pushed branches' setting on travis is ON (see note in top of docs [here](https://docs.travis-ci.com/user/caching/))

**Comment by filmaj** [comment]
FYI I am working on this over here on my fork: https://github.com/filmaj/adobe-stock-integration/pull/4

**Comment by filmaj** [comment]
Got pretty far on this yesterday: HTTPS is set up, but it looks like we are hitting a [maximum travis build timeout (of 50 minutes)](https://docs.travis-ci.com/user/customizing-the-build/#build-timeouts). Check out the build here: https://travis-ci.com/filmaj/adobe-stock-integration/builds/136647231

So far about ~half of the tests are able to run inside the timeout window. So probably need to look into optimization approaches. It looks to me like many `waitForPageLoad`s are taking long but that needs confirmation.

I wonder if it would be possible to split up the test runs across multiple build jobs, maybe using build matrices...
